package work.fking.pangya.game.room

enum class RoomJoinError(val value: Int) {
    ROOM_FULL(2),
    ROOM_DOES_NOT_EXIST(3),
    INCORRECT_PASSWORD(4),
    CANNOT_ENTER_OR_MAKE_WITH_CURRENT_LEVEL(5),
    ROOM_CREATION_FAILED(7),
    GAME_ALREADY_STARTED(8),
    NEED_GUILD_REGISTRATION(13),
    INSUFFICIENT_FUNDS_PANG_BATTLE(15),
    INSUFFICIENT_FUNDS_APPROACH(17),
    CANNOT_CREATE_ROOM_HERE(18)
}