/*
 * This file is generated by jOOQ.
 */
package work.fking.pangya.game.persistence.jooq.tables.records


import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record4
import org.jooq.Row4
import org.jooq.impl.UpdatableRecordImpl

import work.fking.pangya.game.persistence.jooq.tables.PlayerInventoryCard


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PlayerInventoryCardRecord private constructor() : UpdatableRecordImpl<PlayerInventoryCardRecord>(PlayerInventoryCard.PLAYER_INVENTORY_CARD), Record4<Int?, Int?, Int?, Int?> {

    open var uid: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var accountUid: Int
        set(value): Unit = set(1, value)
        get(): Int = get(1) as Int

    open var iffId: Int
        set(value): Unit = set(2, value)
        get(): Int = get(2) as Int

    open var quantity: Int?
        set(value): Unit = set(3, value)
        get(): Int? = get(3) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row4<Int?, Int?, Int?, Int?> = super.fieldsRow() as Row4<Int?, Int?, Int?, Int?>
    override fun valuesRow(): Row4<Int?, Int?, Int?, Int?> = super.valuesRow() as Row4<Int?, Int?, Int?, Int?>
    override fun field1(): Field<Int?> = PlayerInventoryCard.PLAYER_INVENTORY_CARD.UID
    override fun field2(): Field<Int?> = PlayerInventoryCard.PLAYER_INVENTORY_CARD.ACCOUNT_UID
    override fun field3(): Field<Int?> = PlayerInventoryCard.PLAYER_INVENTORY_CARD.IFF_ID
    override fun field4(): Field<Int?> = PlayerInventoryCard.PLAYER_INVENTORY_CARD.QUANTITY
    override fun component1(): Int? = uid
    override fun component2(): Int = accountUid
    override fun component3(): Int = iffId
    override fun component4(): Int? = quantity
    override fun value1(): Int? = uid
    override fun value2(): Int = accountUid
    override fun value3(): Int = iffId
    override fun value4(): Int? = quantity

    override fun value1(value: Int?): PlayerInventoryCardRecord {
        set(0, value)
        return this
    }

    override fun value2(value: Int?): PlayerInventoryCardRecord {
        set(1, value)
        return this
    }

    override fun value3(value: Int?): PlayerInventoryCardRecord {
        set(2, value)
        return this
    }

    override fun value4(value: Int?): PlayerInventoryCardRecord {
        set(3, value)
        return this
    }

    override fun values(value1: Int?, value2: Int?, value3: Int?, value4: Int?): PlayerInventoryCardRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        return this
    }

    /**
     * Create a detached, initialised PlayerInventoryCardRecord
     */
    constructor(uid: Int? = null, accountUid: Int, iffId: Int, quantity: Int? = null): this() {
        this.uid = uid
        this.accountUid = accountUid
        this.iffId = iffId
        this.quantity = quantity
        resetChangedOnNotNull()
    }
}
