/*
 * This file is generated by jOOQ.
 */
package work.fking.pangya.game.persistence.jooq.tables


import java.util.function.Function

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row11
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.jooq.jackson.extensions.converters.JSONtoJacksonConverter

import work.fking.pangya.game.persistence.jooq.Public
import work.fking.pangya.game.persistence.jooq.indexes.IDX_PLAYER_CHARACTER
import work.fking.pangya.game.persistence.jooq.keys.PLAYER_CHARACTER_PKEY
import work.fking.pangya.game.persistence.jooq.keys.PLAYER_CHARACTER__FK_PLAYER_CHARACTER__ACCOUNT
import work.fking.pangya.game.persistence.jooq.tables.records.PlayerCharacterRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PlayerCharacter(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, PlayerCharacterRecord>?,
    aliased: Table<PlayerCharacterRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<PlayerCharacterRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.player_character</code>
         */
        val PLAYER_CHARACTER: PlayerCharacter = PlayerCharacter()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<PlayerCharacterRecord> = PlayerCharacterRecord::class.java

    /**
     * The column <code>public.player_character.uid</code>.
     */
    val UID: TableField<PlayerCharacterRecord, Int?> = createField(DSL.name("uid"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.player_character.account_uid</code>.
     */
    val ACCOUNT_UID: TableField<PlayerCharacterRecord, Int?> = createField(DSL.name("account_uid"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.player_character.iff_id</code>.
     */
    val IFF_ID: TableField<PlayerCharacterRecord, Int?> = createField(DSL.name("iff_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.player_character.hair_color</code>.
     */
    val HAIR_COLOR: TableField<PlayerCharacterRecord, Int?> = createField(DSL.name("hair_color"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.player_character.part_iff_ids</code>.
     */
    val PART_IFF_IDS: TableField<PlayerCharacterRecord, IntArray?> = createField(DSL.name("part_iff_ids"), SQLDataType.JSON.nullable(false), this, "", JSONtoJacksonConverter<IntArray>(IntArray::class.java))

    /**
     * The column <code>public.player_character.part_uids</code>.
     */
    val PART_UIDS: TableField<PlayerCharacterRecord, IntArray?> = createField(DSL.name("part_uids"), SQLDataType.JSON.nullable(false), this, "", JSONtoJacksonConverter<IntArray>(IntArray::class.java))

    /**
     * The column <code>public.player_character.aux_parts</code>.
     */
    val AUX_PARTS: TableField<PlayerCharacterRecord, IntArray?> = createField(DSL.name("aux_parts"), SQLDataType.JSON.nullable(false), this, "", JSONtoJacksonConverter<IntArray>(IntArray::class.java))

    /**
     * The column <code>public.player_character.cutin_iff_id</code>.
     */
    val CUTIN_IFF_ID: TableField<PlayerCharacterRecord, Int?> = createField(DSL.name("cutin_iff_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.player_character.stats</code>.
     */
    val STATS: TableField<PlayerCharacterRecord, IntArray?> = createField(DSL.name("stats"), SQLDataType.JSON.nullable(false), this, "", JSONtoJacksonConverter<IntArray>(IntArray::class.java))

    /**
     * The column <code>public.player_character.mastery</code>.
     */
    val MASTERY: TableField<PlayerCharacterRecord, Int?> = createField(DSL.name("mastery"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.player_character.cards</code>.
     */
    val CARDS: TableField<PlayerCharacterRecord, IntArray?> = createField(DSL.name("cards"), SQLDataType.JSON.nullable(false), this, "", JSONtoJacksonConverter<IntArray>(IntArray::class.java))

    private constructor(alias: Name, aliased: Table<PlayerCharacterRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<PlayerCharacterRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.player_character</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.player_character</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.player_character</code> table reference
     */
    constructor(): this(DSL.name("player_character"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, PlayerCharacterRecord>): this(Internal.createPathAlias(child, key), child, key, PLAYER_CHARACTER, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IDX_PLAYER_CHARACTER)
    override fun getIdentity(): Identity<PlayerCharacterRecord, Int?> = super.getIdentity() as Identity<PlayerCharacterRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<PlayerCharacterRecord> = PLAYER_CHARACTER_PKEY
    override fun getReferences(): List<ForeignKey<PlayerCharacterRecord, *>> = listOf(PLAYER_CHARACTER__FK_PLAYER_CHARACTER__ACCOUNT)

    private lateinit var _account: Account

    /**
     * Get the implicit join path to the <code>public.account</code> table.
     */
    fun account(): Account {
        if (!this::_account.isInitialized)
            _account = Account(this, PLAYER_CHARACTER__FK_PLAYER_CHARACTER__ACCOUNT)

        return _account;
    }

    val account: Account
        get(): Account = account()
    override fun `as`(alias: String): PlayerCharacter = PlayerCharacter(DSL.name(alias), this)
    override fun `as`(alias: Name): PlayerCharacter = PlayerCharacter(alias, this)
    override fun `as`(alias: Table<*>): PlayerCharacter = PlayerCharacter(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): PlayerCharacter = PlayerCharacter(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): PlayerCharacter = PlayerCharacter(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): PlayerCharacter = PlayerCharacter(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row11<Int?, Int?, Int?, Int?, IntArray?, IntArray?, IntArray?, Int?, IntArray?, Int?, IntArray?> = super.fieldsRow() as Row11<Int?, Int?, Int?, Int?, IntArray?, IntArray?, IntArray?, Int?, IntArray?, Int?, IntArray?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Int?, Int?, Int?, Int?, IntArray?, IntArray?, IntArray?, Int?, IntArray?, Int?, IntArray?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Int?, Int?, Int?, Int?, IntArray?, IntArray?, IntArray?, Int?, IntArray?, Int?, IntArray?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
